### ISSUE TITLE
refactor: consider sharedFD

### ISSUE THREAD

**Issue by brekelj1** [go-mod-proxy/go-mod-proxy#52]
It seems that all uses of https://github.com/go-mod-proxy/go-mod-proxy/blob/01a4c5930a84ee48f7a0fba131a943aeefccd22f/go/internal/pkg/service/gomodule/gocmd/sharedfd.go#L17 (there's only 2 uses) can be replaced by https://github.com/go-mod-proxy/go-mod-proxy/blob/01a4c5930a84ee48f7a0fba131a943aeefccd22f/go/internal/pkg/service/gomodule/gocmd/tempgoenv.go#L112
so we can simplify the code and delete `sharedfd.go`.

**Comment by jbrekelmans** [comment]
`newSharedFDOpen` returns an object with ref counting, an d the cleanup logic becomes complex without ref counting.
